apiVersion: v1
kind: Service
metadata:
  labels:
    app: cafefrontend
  name: cafefrontend
spec:
  ports:
  - name: 3000-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cafefrontend
  type: LoadBalancer
